import { SysAccountsService } from './sysAccountsService';
import { SysAuditLogService } from './sysAuditLogService';
import { SysCheckpointsService } from './sysCheckpointsService';
import { SysFeaturesService } from './sysFeaturesService';
import { SysInsightsService } from './sysInsightsService';
import { SysMembersService } from './sysMembersService';
import { SysRuleTemplatesService } from './sysRuleTemplatesService';
import { SysRulesService } from './sysRulesService';
import { SysStreamsService } from './sysStreamsService';
import { SysUsersService } from './sysUsersService';
import { UsrInsightsService } from './usrInsightsService';
import { UsrIntegrationsService } from './usrIntegrationsService';
import { UserService } from './userService';
import { DevicesService } from './devicesService';
import { EventsService } from './eventsService';
import { ReportsService } from './reportsService';
import { RulesService } from './rulesService';
export declare const Services: (typeof SysAccountsService | typeof SysAuditLogService | typeof SysCheckpointsService | typeof SysFeaturesService | typeof SysInsightsService | typeof SysMembersService | typeof SysRuleTemplatesService | typeof SysRulesService | typeof SysStreamsService | typeof SysUsersService | typeof UsrInsightsService | typeof UsrIntegrationsService | typeof UserService | typeof DevicesService | typeof EventsService | typeof ReportsService | typeof RulesService)[];
