import { EventStatusCode } from '../enums';
import { Indicator } from '../common';
import { GeoData } from '../common';
import { StringKeyValue } from '../common';
import { EventOccurrence } from '../entities';
import { TrafficDirectionCode } from '../enums';
import { Device } from '../entities';
import { SeverityTypeCode } from '../enums';
import { BaseEntity } from '../base';
import { RuleTypeCode } from '../enums';
import { EventCategoryCode } from '../enums';
import { EventTypeCode } from '../enums';
export declare class EventWithDevice extends BaseEntity {
    accountId: string;
    streamId: string;
    deviceId: string;
    startTime: number;
    endTime: number;
    type: EventTypeCode;
    severity: SeverityTypeCode;
    score: number;
    probability: number;
    status: EventStatusCode;
    indicators: Indicator[];
    ruleType: RuleTypeCode;
    ruleId: string;
    targetIp: string;
    targetLocation: GeoData;
    description: string;
    tags: string[];
    labels: StringKeyValue[];
    category: EventCategoryCode;
    recommendedAction: string;
    occurrences: EventOccurrence[];
    trafficDirection: TrafficDirectionCode;
    confidenceScore: number;
    occurrencesCount: boolean;
    device: Device;
}
