import { BaseEntity } from '../base';
import { IntegrationTypeCode } from '../enums';
import { IntegrationTriggerCode } from '../enums';
import { HttpMethodCode } from '../enums';
import { StringKeyValue } from '../common';
import { EventTypeCode } from '../enums';
import { SeverityTypeCode } from '../enums';
import { DeviceActionCode } from '../enums';
export declare class Integration extends BaseEntity {
    accountId: string;
    streamId: string;
    type: IntegrationTypeCode;
    trigger: IntegrationTriggerCode;
    name: string;
    enabled: boolean;
    host: string;
    port: number;
    user: string;
    password: string;
    url: string;
    method: HttpMethodCode;
    headers: StringKeyValue[];
    mimeType: string;
    recipients: string[];
    subject: string;
    body: string;
    from: string;
    eventTypes: EventTypeCode[];
    eventSeverity: SeverityTypeCode;
    preventiveAction: DeviceActionCode;
}
