import { BaseEntity } from '../entities/BaseEntity';
export declare class UsageRecord extends BaseEntity {
    source: string;
    accountId: string;
    streamId: string;
    deviceId: string;
    deviceIp: string;
    simId: string;
    startTime: number;
    endTime: number;
    srcPortsList: number[];
    srcPortsCount: number;
    dstPortsList: number[];
    dstPortsCount: number;
    endpointsList: string[];
    endpointsCount: number;
    srcEndpoints: string[];
    dstEndpoints: string[];
    packetsIn: number;
    packetsOut: number;
    bytesIn: number;
    bytesOut: number;
    srcAckFlags: number;
    dstAckFlags: number;
    srcSynFlags: number;
    dstSynFlags: number;
    srcRstFlags: number;
    dstRstFlags: number;
    labels: string[];
}
